/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_example_cameralib_SkyBoxView_SkyBoxController */

#ifndef SkyBoxController
#define SkyBoxController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cameralib_SkyBoxView_SkyBoxController
 * Method:    initGLEnv
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL skyBoxInit
  (JNIEnv *env, jobject obj, jobject surface);

/*
 * Class:     com_example_cameralib_SkyBoxView_SkyBoxController
 * Method:    cameraRenderResetSize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL skyBoxRenderResetSize
  (JNIEnv *env, jobject obj, jint left, jint top, jint width, jint height);

/*
 * Class:     com_example_cameralib_SkyBoxView_SkyBoxController
 * Method:    skyBoxRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL skyBoxRelease
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
