/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cameralib_SmlCameraPreviewRenderController */

#ifndef SmlCameraPreviewRenderController
#define SmlCameraPreviewRenderController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cameralib_SmlCameraPreviewRenderController
 * Method:    initGLEnv
 * Signature: (Ljava/lang/Object;IIII)Z
 */
JNIEXPORT jboolean JNICALL cameraRenderInit
    (JNIEnv *env, jobject obj, jobject surface, jint left, jint top, jint width, jint height);

/*
 * Class:     com_example_cameralib_SmlCameraPreviewRenderController
 * Method:    cameraRenderResetSize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL cameraRenderResetSize
  (JNIEnv *env, jobject obj, jint left, jint top, jint width, jint height);

/*
 * Class:     com_example_cameralib_SmlCameraPreviewRenderController
 * Method:    cameraRenderStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL cameraRenderStop
  (JNIEnv *env, jobject obj);

/*
 * Class:     com_example_cameralib_SmlCameraPreviewRenderController
 * Method:    requestCameraRender
 * Signature: ([BJJJ)V
 */
JNIEXPORT void JNICALL requestCameraRender
   (JNIEnv *env, jobject obj, jbyteArray data, jlong len, jlong preWidth, jlong preHeight);

#ifdef __cplusplus
}
#endif
#endif
