/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cameralib_SkyBoxController */

#ifndef _Included_com_example_cameralib_SkyBoxController
#define _Included_com_example_cameralib_SkyBoxController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cameralib_SkyBoxController
 * Method:    skyBoxInit
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_cameralib_SkyBoxController_skyBoxInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_cameralib_SkyBoxController
 * Method:    skyBoxResetSize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_cameralib_SkyBoxController_skyBoxResetSize
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_example_cameralib_SkyBoxController
 * Method:    skyBoxRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_cameralib_SkyBoxController_skyBoxRelease
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
